### ISSUE TITLE
powerlineを統合する

### ISSUE THREAD

**Issue by ryosan-470** [ryosan-470/dotfiles#8]
Powerlineを以下のリポジトリに統合する.

https://github.com/powerline/powerline/

**Comment by jtwp470** [comment]
Vim側は上記powerlineは使わず vim-airlineを利用することにしたので実質zshとtmuxのみ上を使う予定.

**Comment by ryosan-470** [comment]
統合ってなんぞって感じになってきたので一旦クローズ
